version: 1.20.0.'{build}'
skip_tags: true
image: Visual Studio 2019
clone_depth: 3
environment:
  AWS_ACCESS_KEY_ID:
    secure: 7jhk0oV/vjFsOcsAHLMUcNGUGLuGmnuPxGH0ce/Vky8=
  AWS_SECRET_ACCESS_KEY:
    secure: 5KKYpsIHwYHHh5ud0U7Ss0rLumv6G8tkS6abh1B9aq4wY6+1kq5fN/3E5BsdBVKy
  AWS_DEFAULT_REGION: us-east-1
  S3_CONFIG_VOLATILE: --acl public-read --cache-control "public, must-revalidate, proxy-revalidate, max-age=0"
  GIT_FORMAT: '%%H'
  matrix:
  - ARCH: x64
    PLATFORM: x64
  - ARCH: x86
    PLATFORM: Win32
matrix:
  fast_finish: true
build_script:
- cmd: >-
    cd build

    cmake -G "Visual Studio 16 2019" -A %PLATFORM% -DALSOFT_REQUIRE_WINMM=ON -DALSOFT_REQUIRE_DSOUND=OFF -DALSOFT_REQUIRE_WASAPI=ON -DALSOFT_EMBED_HRTF_DATA=ON ..

    cmake --build . --config Release

    aws s3 cp Release\OpenAL32.dll s3://build.lwjgl.org/nightly/windows/%ARCH%/OpenAL.dll %S3_CONFIG_VOLATILE%

    cd ..

    git log --first-parent --pretty=format:%GIT_FORMAT% HEAD~2..HEAD~1 > revision.git

    aws s3 cp revision.git s3://build.lwjgl.org/nightly/windows/%ARCH%/OpenAL.dll.git %S3_CONFIG_VOLATILE%
test: off
notifications:
- provider: Email
  to:
  - iotsakp@gmail.com
  subject: OpenAL-Soft CI
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true